language: node_js
node_js:
  - '4'
sudo: false
script:
  - "npm run test-cov"
after_script: "npm install coveralls && cd test &&  cat coverage.lcov | ../node_modules/coveralls/bin/coveralls.js && cd .."